language: python
python:
  - "3.6"
env:
  - REPO=lyft/metadataproxy
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
install: "pip install -r requirements.txt"
script: make test
after_success:
  - ./docker_push.sh
deploy:
  provider: pypi
  user: lyftpypi
  password:
    secure: G+ArrevNqoLwg8wmxKoL+E4JjCKxxZMDakntKi9s111fQJxLkqtcs/k0X/j3XSxzQC7N2nzY4upcoEghvlo+tiCfqO2KJTEtBTcK5BtxXEchQk/Czn6Z5OhymS1SaZ/sQ1XO9mr2m5PR1vKJculm+kRPRfyRxIKMU6CH6Z306uJJejXtmNb1ONvBLWNm3GbaCpV4k4Hx9X0EbdhxDHbhOlpyyQtuR3olacfgbXnZp2NRhKtxEKMzoshQmg36nr55w/nzy34Uxa7u6W8+/WP5Gc8FZ45gy+IVwonguTnBSY55ywlK/geC6hOoXRa86HInLKLWvUvmaOrmAjli6pC4UXKX6fWlJw+rNFZZ2KuiVX/PUhrTBIcN2xXjFZEjstJTbItVbPFbEVMD0YrStd9sli1AooC5wuhGgnqD68YqNtqKVJWcgjgeHpKEGdb4OriDN9LYuxeVQG9TaOqOZVR7AQ693Yrpk9gqslDcxrjI4GO46G3CSGVEhYmVZQ3AVn3xVALj3iQQ+xhj9Hdu8WxXlR46ZMQqkKPgRYFtjklRBwzK7rJ3OXeV6cMpO77vAEqcj/jD4sgzRTOkY03rHYEe7gscZlOgAkPrJbY/lBJW19ckQTBxjHLpPh8+wp8ADT9Qz64lKOd54lrKXvi0zcXpOMURMDaFssaHWg+trKRxLFQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/metadataproxy
