language: python
python:
  - "3.6"
env:
  - REPO=lyft/metadataproxy
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
install: "pip install -r requirements.txt"
script: make test
after_success:
  - ./docker_push.sh
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "bxMMtYzLBrDZT9TskiJoeAPKny/sfeGdCAmELIQVgwJuj070bFxba5NnRRmtAcN8lOAsrn+MrP2LWglhcsMOlCIu/mmLt/rhVy3DO7XzCHpSPUvkOCrRIgvmw6yPR6Qc/B4KkWRuSsAijAo1wtL3QYmO0uW4V7ikjgjCF7OnBI+szWbLaffpwHB7rIijlnGBfUMQzaw3aa5HmHJ+ByBOkzwYI3NZu6hOGMMTrBPOmhOmQ2pTFogUcONp5fETCXcg2YQQkRjEtrgclFTHM+PxVAtylmzXDYfNxSea44FOuANOqIsk5Re3R/YtVvzVPyXS4ZM4jlOkD+Yl01HnspEnWpUkKMfKSK9xrXCKGFXHv/Wjgw+5nu+thHJtLABS4Dh59V8xARqU5B78r9e2Loe4CzpTdBN7dzeewORTleSZ8iJFnDz3Lljanc5KToRL+I4WE9JzSgtLFPKNXpBMAy7bIb89uVVsrmZBvvcNp0FPGwGzujVugy90oTpQ3gyCL107pnx79nWPg0sLMQDl/hU4PA6sD8FWFdRgMfcf9LGKw6xBcLb5DhWH9QCzwgN03PB5JkXVyE09aeWh+N1+4twCtdyC+VX1Enjd/HXTjAeuPi59MRgcmDNCvjyW5j3PLd4F54dcpbCpPzoLyZZE4xFVH6u46aVzSafzM1RAnz6knFI="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/metadataproxy
